### ISSUE TITLE
Request: Update mods.toml File for Curios Dependency

### ISSUE THREAD

**Issue by YassaaaTU** [juancarloscp52/spyglass-improvements#69]
I am experiencing incompatibility issues with the Accessories mod and the compat layer for Curio. It seems that specifying a version range for the Curios dependency in the `mods.toml` file located in the `META-INF` directory is causing these issues. 

Could you please update the `mods.toml` file to require a version of Curios from a specific version and higher, instead of using a range? This change should help resolve the compatibility problems.

For reference, this issue is related to [Issue #61](https://github.com/juancarloscp52/spyglass-improvements/issues/61).

Here is an example of how the change can be implemented:

```toml
[[dependencies.spyglass_improvements]]
modId="curios"
mandatory=false
versionRange="[5.2,)"
ordering="BEFORE"
side="BOTH"
```
